### ISSUE TITLE
Possible typo 

### ISSUE THREAD

**Issue by poorvi4** [zktuong/ktplots#23]
Hi all,

First off, just wanted to say thank you for creating this package! I find the visualization extremely helpful in comparison to the default  CellphoneDB heatmap/dotplots. After playing around with some of the functions, I've been encountering issues with the plot_cpbdb2 function in which I receive the following error message: `Error in findComplex(interactions_subset) : object 'complex_b' not found.`

 Here's the following code I ran:
`
test <- plot_cpdb2(cell_type1 = "Podo", # same usage style as plot_cpdb
	cell_type2 = "LOH",
	idents = 'predicted.Main_cell_type',
	scdata = d197.sce,
	means = means,
	pvals = pvalues,
	deconvoluted = deconvoluted,
    keep_significant_only = TRUE,
    standard_scale = TRUE,
    remove_self = TRUE)
test
`
where d197.sce is a single cell object. Looking at the findComplex subfunction in the original function code, I noticed the following around line 118:
`
 if (length(complexa) > 0) {
            if (length(complexb) > 0) {
                res <- c(complexa, complex_b)
            }
            else {
                res <- complexa
            }
        }
        else if (length(complexb) > 0) {
            res <- complexb
        }
        else {
            res <- NULL
        }
        return(res)
    }
` 
Not sure if the variable complex_b is a typo for complexb as it's not referenced anywhere else in the code. Changing this variable name to complexb then results in this error:
<img width="956" alt="Screen Shot 2021-11-04 at 4 34 47 PM" src="https://user-images.githubusercontent.com/41170744/140434537-3873d7e0-e544-41a9-8463-19e79577b381.png">

Not sure if there is an issue with my function parameters. Any suggestions are welcome :)
Thank you!

**Comment by aokhan** [comment]
Hi @poorvi4 and @zktuong 

I've run into the same issue! Error is: Error in findComplex(interactions_subset) : object 'complex_b' not found


I also wanted to ask where I could find the 'interaction_groupings.txt' file? Can't seem to find it anywhere. 

Thanks in advance =)

**Comment by zktuong** [comment]
Hi both, thank you for using this package! 

I think you're right that it's probably a typo and should be `complexb` the whole way through. About what happens afterwards, I need to do a bit of debugging and will track this at #24. When i do come up with a fix later (and i'll notify here), you can uninstall (`remove.packages`) and install with:

```R
devtools::install_github('zktuong/ktplots', ref = "fix_typo")
```

@aokhan For `interaction_groupings.txt`, it's a file you have to generate yourself based on the interactions that you want to visualise. For my use case, I only had to select a few interactions and i've uploaded it here (I've called it `roles.txt`)
[roles.txt](https://github.com/zktuong/ktplots/files/7485730/roles.txt)

As this list is not the full list, I've created a google drive to accumulate this over time and you are welcomed to contributed to it:
https://docs.google.com/spreadsheets/d/1O9OKU7J0NdeQNJAIMpsHtWAFvY014GDQ7aigdGUSTmc/edit?usp=sharing

Let me know if you have any solutions and feel free to open a PR if you get to it before i do.

**Comment by aokhan** [comment]
@zktuong thanks for the quick response! Excited to get this to work, so much better for plotting than what's out there at the moment. 

We will wait to hear from you hope it isn't too much hassle to fix =)

Thanks for that file - will go through and add. I will run this in the first instance probably without interaction groupings!

**Comment by zktuong** [comment]
update - So changing the typo doesn't seem to affect my use case. 

@poorvi, does the original `plot_cpdb` with the same cell types and settings work by itself? 

I will upload a test dataset soon to match with `kidneyimmune` and `cpdb_output` that can be used to test `plot_cpdb2` shortly.

**Comment by aokhan** [comment]
@zktuong I have been able to run plot_cpdb with no problems so far!

**Comment by zktuong** [comment]
Sorry both. I think `plot_cpdb2` is far from being fully functional. At the moment it seems to work only when `split.by` is being used, which is not ideal. It also only works if cellphonedb was ran using ensg ids rather than with gene symbols.

I'll need quite a bit of time and focus to untangle some of the esoteric code to make it potentially usable.

**Comment by aokhan** [comment]
@zktuong no worries mate, it'll be worth it hopefully in the end. 
I'm not sure how my CellPhoneDB was run, I can look into it. 
I can use 'split.by' if I can add a column with identifiers based on cluster assignment. I've got a fair few subsets of clusters, so can pool them into 'stroma' etc, and then use 'split.by' Any suggestions for how to add a column to an SCE object that will achieve this? I'll look into working this out myself but thought I would ask while here =) 

Thanks again for all your efforts. 

BW
Abs

**Comment by zktuong** [comment]
@aokhan If i'm interpreting your questions correctly, you will need to adjust your `meta.txt` that was used to run the cellphonedb before you can use the `split.by` option here. 

assuming you have an SCE object, then `colData(sce)[,'new_column'] = paste0(colData(sce)[,'columnA'], '_', colData(sce)[,'columnB'])` should work to create the new column. Then you just make a new `meta.txt` with the new column and run it. When you want to run `plot_cpdb`,  then it should be `split.by = 'columnA', ident = 'columnB'`.

**Comment by aokhan** [comment]
Thanks a lot @zktuong !

**Comment by aokhan** [comment]
@zktuong  not sure what the etiquette is re asking questions about this. Do I keep posting on this thread or is there a better way to get in touch? (If you don't mind me doing so). 

I've re-run cellphone DB on my data using ENSEMBL IDs and with meta data that includes 'type' as an option I can use to split.by... In theory I should now be able to use plot_cpdb2 if I understand the above correctly. 

I've had a go and get a row mismatch error: 
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 219, 229
> traceback()
5: stop(gettextf("arguments imply differing number of rows: %s", 
       paste(unique(nrows), collapse = ", ")), domain = NA)
4: data.frame(..., check.names = FALSE)
3: cbind(deparse.level, ...)
2: cbind(interactions_subset, tm0)
1: plot_cpdb2(cell_type1 = "cl10", cell_type2 = "cl9", idents = "clustering", 
       split.by = "type", scdata = sce, means = means, pvals = pvalues, 
       deconvoluted = deconvoluted, gene_symbol_mapping = "Gene", 
       node_group_colors = c(cl9 = "#86bc86", cl10 = "#79706e"), 
       keep_significant_only = TRUE, standard_scale = TRUE, remove_self = TRUE)
> 

I can't really see where a mismatch of rows could be coming from. Could it be my sce object? 

If there's an easier way to communicate please let me know - thanks for all your help. 
Abs

**Comment by zktuong** [comment]
@aokhan @poorvi4 

I think i cracked it. Can you please try to reinstall the devel version and see if it works now?

```R
devtools::install_github('zktuong/ktplots', ref = "fix_typo")
```

i have a test example in my test folder and you can try and modify it to see if anything breaks:


```R
data(kidneyimmune)
data(cpdb_output) # this one can be used if specifying split.by = 'Experiment'
data(cpdb_output2) # this one can be used if  specifying split.by = NULL

sce <- Seurat::as.SingleCellExperiment(kidneyimmune)
# test 1
p <- plot_cpdb2(cell_type1 = 'B cell', cell_type2 = 'CD4T cell', 
        scdata = sce,
        idents = 'celltype', # column name where the cell ids are located in the metadata
        means = means2, 
        pvals = pvals2,
        deconvoluted = decon2, # new options from here on specific to plot_cpdb2
        desiredInteractions = list(
            c('CD4T cell', 'B cell'), 
            c('B cell', 'CD4T cell')),
        interaction_grouping = interaction_annotation,
        edge_group_colors = c(
            "Activating" = "#e15759", 
            "Chemotaxis" = "#59a14f", 
            "Inhibitory" = "#4e79a7", 
            "Intracellular trafficking" = "#9c755f",
            "DC_development" = "#B07aa1",
            "Unknown" = "#e7e7e7"
            ),
        node_group_colors = c(
            "CD4T cell" = "#86bc86", 
            "B cell" = "#79706e"),
        keep_significant_only = TRUE,
        standard_scale = TRUE,
        remove_self = TRUE
        )

## test 2
p <- plot_cpdb2(cell_type1 = 'B cell', cell_type2 = 'CD4T cell', 
        scdata = sce,
        idents = 'celltype', # column name where the cell ids are located in the metadata
        split.by = 'Experiment', # column name where the grouping column is. Optional.
        means = means, 
        pvals = pvals,
        deconvoluted = decon, # new options from here on specific to plot_cpdb2
        desiredInteractions = list(
            c('CD4T cell', 'B cell'), 
            c('B cell', 'CD4T cell')),
        interaction_grouping = interaction_annotation,
        edge_group_colors = c(
            "Activating" = "#e15759", 
            "Chemotaxis" = "#59a14f", 
            "Inhibitory" = "#4e79a7", 
            "Intracellular trafficking" = "#9c755f",
            "DC_development" = "#B07aa1",
            "Unknown" = "#e7e7e7"
            ),
        node_group_colors = c(
            "CD4T cell" = "#86bc86", 
            "B cell" = "#79706e"),
        keep_significant_only = TRUE,
        standard_scale = TRUE,
        remove_self = TRUE
        )
```

**Comment by aokhan** [comment]
@zktuong Thanks Kelvin! I'm a bit chocca for a couple of days but will do try this asap!
I had reformatted and re-run my CellPhoneDB Analysis with ENSEMBL IDs instead of Gene names anda. meta column to run split.by. After meeting with some colleagues I need to tweak some of my clusters, so need to re run this again. Would you suggest I stick to running with ENSEMBL IDs and a column with which to run split.by?

Thanks for your time and efforts on this. 
Abs

**Comment by zktuong** [comment]
Yes i think that's the best - the original cellphonedb was created with using the ensembl ids as the design.

**Comment by aokhan** [comment]
@zktuong Just getting to this today! 

I've run your example but get this error: 

Error in loadNamespace(name) : there is no package called ‘kelvinny’

I've run the following: 

data(kidneyimmune)
data(cpdb_output) # this one can be used if specifying split.by = 'Experiment'
data(cpdb_output2) # this one can be used if  specifying split.by = NULL

sce <- Seurat::as.SingleCellExperiment(kidneyimmune)
# test 1
p <- plot_cpdb2(cell_type1 = 'B cell', cell_type2 = 'CD4T cell', 
        scdata = sce,
        idents = 'celltype', # column name where the cell ids are located in the metadata
        means = means2, 
        pvals = pvals2,
        deconvoluted = decon2, # new options from here on specific to plot_cpdb2
        desiredInteractions = list(
            c('CD4T cell', 'B cell'), 
            c('B cell', 'CD4T cell')),
        #interaction_grouping = interaction_annotation,
        #edge_group_colors = c(
         #   "Activating" = "#e15759", 
         #   "Chemotaxis" = "#59a14f", 
          #  "Inhibitory" = "#4e79a7", 
         #   "Intracellular trafficking" = "#9c755f",
           # "DC_development" = "#B07aa1",
           # "Unknown" = "#e7e7e7"
          #  ),
        node_group_colors = c(
            "CD4T cell" = "#86bc86", 
            "B cell" = "#79706e"),
        keep_significant_only = TRUE,
        standard_scale = TRUE,
        remove_self = TRUE
        )

I just commented out the interaction mapping bit as I don't have the .txt file - but can download and set that up if you think commenting that out breaks it? 

Any thoughts ?

**Comment by zktuong** [comment]
oops sorry. Fixed that now. It was a colouring issue that i was using to get ggplot-style colours.

**Comment by aokhan** [comment]
@zktuong aha no problem! I take it i will need to re-run devtools::install_github('zktuong/ktplots', ref = "fix_typo") to correct this?

**Comment by zktuong** [comment]
I've also pushed the commit to master now, so can just install the normal way.

**Comment by aokhan** [comment]
@zktuong thanks! I'm having some trouble but not sure if it's an R thing on my end. Will be in touch!

Again thanks a lot for your time! hopefully get somewhere in the next couple of days =)

**Comment by zktuong** [comment]
hi @aokhan that means it's working. it was just my poor choice of colours here under:
```R
node_group_colors = c(
            "CD4T cell" = "#86bc86", 
            "B cell" = "#79706e"),
```
If `interaction_grouping` option is not provided, then the lines will just be black as well.

**Comment by aokhan** [comment]
Morning @zktuong - so everything looks fine with the sample data, I commented out plenty of lines and can still get a plot.

I tried running my own data and hit an error I've not come across before:
Error in hclust(d) : NA/NaN/Inf in foreign function call (arg 10)

Is this something you've come across before?

**Comment by zktuong** [comment]
I don't think that's a bug per se - it's got to do with `plot_cpdb` - can you try running this and see if it works? the issue is most likely either 1) there's no significant hits (or there's no rows to do the clustering just before plotting) (most likely), 2) there's an unexpected NA, 3) all the columns have the same value (least likely).

**Comment by aokhan** [comment]
Sure thanks - I had run plot_cpdb successfully yesterday, but I'll work through everything to see where the problem is this morning and get back to you =) will be a bit slapdash as in the lab a lot today

**Comment by zktuong** [comment]
Just flagging that `plot_cpdb2` it's still buggy - it's missing a few interactions and i need to work out why

**Comment by zktuong** [comment]
> Just flagging that `plot_cpdb2` it's still buggy - it's missing a few interactions and i need to work out why

ok monkey patched it for now. `labels` are still a bit of an issue, but more or less solveable as the `name` slot exist in the plotting data.

**Comment by zktuong** [comment]
tracking at #26

**Comment by aokhan** [comment]
Hey @zktuong ! Could I clarify what you mean by: 

labels are still a bit of an issue, but more or less solveable as the name slot exist in the plotting data.

Thanks
Abs

**Comment by zktuong** [comment]
> labels are still a bit of an issue, but more or less solveable as the name slot exist in the plotting data.

Hard to explain - I don't see it as a huge issue regardless. 

It's just a plotting thing that can overcomed by switching the `geom_text_repel(aes(x=x, y=y, label = label)` portion to `geom_text_repel(aes(x=x, y=y, label = name)` in the last bit of the plotting.

**Comment by zktuong** [comment]
oh and also, i'm adding a couple of other bug fix. 
please install with:
`devtools::install_github('zktuong/ktplots', ref = 'fix_plot_cpdb2')`

**Comment by aokhan** [comment]
Aha thank you @zktuong I've installed. 

I had some problems within my R environment and had to reinstall and fix a few things, but it's all working well now with plot_cpdb. 

When I run plot_cpdb2 like this: 

test <- plot_cpdb2(cell_type1 = 'Megakaryocyte 1', # same usage style as plot_cpdb
                     cell_type2 = 'Endothelium',
                     idents = 'annotations', #idents = colLabels(sce),
                     #split.by = 'type',
                     scdata = sce_2,
                     means = means,
                     pvals = pvalues,
                     deconvoluted = deconvoluted, # new options from here on specific to plot_cpdb2
                     #gene_symbol_mapping = 'gene_symbols',#gene_symbol_mapping = rownames(sce), # column name in rowData holding the actual gene symbols if the row names is ENSG Ids. Might be a bit buggy
                     #desiredInteractions = list(c('cl4', 'cl10')), 
                     #interaction_grouping = interaction_grouping,
                     #edge_group_colors = c("Activating" = "#e15759", "Chemotaxis" = "#59a14f", "Inhibitory" = "#4e79a7", "   Intracellular trafficking" = "#9c755f", "Chemokines" = "#B07aa1"),
                     #node_group_colors = c("cl9" = "#86bc86", "cl10" = "#79706e", "cl4" = '#ff7f0e',"cl13" = '#bcbd22'),
                    node_group_colors = c("Megakaryocyte I" = "#86bc86", "Endothelium" = "#79706e"),
                     keep_significant_only = FALSE,
                     standard_scale = TRUE,
                     remove_self = TRUE)
I get this error: 
**Error in UseMethod("droplevels") : 
  no applicable method for 'droplevels' applied to an object of class "character"**

If I run the same but use split.by("type") then I get this one: 
Error in hclust(d) : NA/NaN/Inf in foreign function call (arg 10)

**Comment by zktuong** [comment]
Thanks i just pushed a fix which should solve the first issue.

the hclust problem is from `plot_cpdb` and seems a bit weird. would you be able to send me a sample of your input files so that i can take a look?

**Comment by aokhan** [comment]
I've installed via: devtools::install_github('zktuong/ktplots') but still have same issue? 

Error in UseMethod("droplevels") :
no applicable method for 'droplevels' applied to an object of class "character"

I don't seem to have the hclust from plot_cpdb, just in plot_cpdb2? What would you like to take a look at? I can DM or email you. 

FYI away for the weekend and at conference Monday so may be a delay in getting back to you from now on! Again thanks so much for all your time on this. Have a good weekend!

**Comment by zktuong** [comment]
hi @aokhan before sending over things, can you try and convert all the columns in your sce object into factors first and see if that helps?

**Comment by aokhan** [comment]
HI @zktuong ! Sorry for the delay was at a conference. I have converted everything and huzzah we have a plot! 

I've run: 
test_plot <- plot_cpdb2(cell_type1 = 'Megakaryocyte 1', # same usage style as plot_cpdb
                     cell_type2 = 'Endothelium',
                     idents = 'annotations', #idents = colLabels(sce),
                     #split.by = 'type',
                     scdata = sce_2,
                     means = means,
                     pvals = pvalues,
                     deconvoluted = deconvoluted, # new options from here on specific to plot_cpdb2
                     #gene_symbol_mapping = 'gene_symbols',#gene_symbol_mapping = rownames(sce), # column name in rowData holding the actual gene symbols if the row names is ENSG Ids. Might be a bit buggy
                     #desiredInteractions = list(c('cl4', 'cl10')), 
                     #interaction_grouping = interaction_grouping,
                     #edge_group_colors = c("Activating" = "#e15759", "Chemotaxis" = "#59a14f", "Inhibitory" = "#4e79a7", "   Intracellular trafficking" = "#9c755f", "Chemokines" = "#B07aa1"),
                     #node_group_colors = c("cl9" = "#86bc86", "cl10" = "#79706e", "cl4" = '#ff7f0e',"cl13" = '#bcbd22'),
                    node_group_colors = c("Megakaryocyte I" = "green", "Endothelium" = "blue"),
                     keep_significant_only = TRUE,
                     standard_scale = TRUE,
                     remove_self = TRUE)
plot(test_plot)

![image](https://user-images.githubusercontent.com/47150680/143011192-f8ba55bf-114b-4d2d-9042-fd1597d18ef7.png)

There are only a couple of issues I can see (for now anyway): 
1. In the plot one of the cell types won't colour, regardless of what I do (green in this example but appears grey)
2. I also get this error before it plots: 
Warning messages:
1: ggrepel: 9 unlabeled data points (too many overlaps). Consider increasing max.overlaps 


If I run it with split.by() I get this error: Error in plot_cpdb(cell_type1 = cell_type1, cell_type2 = cell_type2, scdata = scdata,  : 
  Please check your options for split.by and your celltypes.
the sce does indeed have a column which is factors called 'type' which it shouldn't have a problem with....

Thanks!
Abs

**Comment by zktuong** [comment]
hi @aokhan, 

> In the plot one of the cell types won't colour, regardless of what I do (green in this example but appears grey)

This is indeed weird. What if you remove the node_group_colors option, and use `+ scale_color_manual(...)` as per usual ggplot2's style. My guess at the moment is that perhaps `Megakaryocyte 1` is mispelt somehow? like a space? Can also try and remove spaces and special characters to see if that's the issue.

> I also get this error before it plots:
Warning messages:
1: ggrepel: 9 unlabeled data points (too many overlaps). Consider increasing max.overlaps

This is just a warning, can safely ignore.

> If I run it with split.by() I get this error: 

does your input `meta.txt`'s `cell_type` column looks like this: `{split.by}_{cell_type}`?  If not, you'll have to re-run cellphonedb with that meta.txt looking like that.

**Comment by aokhan** [comment]
Thanks a lot zktuong =) Really appreciate your time and efforts on all of this!

**Comment by aokhan** [comment]
I'll work on this and get back in touch if any more issues =)

**Comment by zktuong** [comment]
no worries. i'll close this issue for now then. if you found a bug, feel free to open a new issue.
Otherwise if it's a usage question, create a post in the discussion tab.
